#!/usr/bin/env bash
# Records the public members System.Text.Json's source generator emits for a
# public JsonSerializerContext, which the RS0016 code fix will not write.
#
#   scripts/record-generated-public-api.sh src/Periphery.Monitor \
#       src/Periphery.Monitor/Serialization/MonitorLayoutJsonContext.cs
#
# Run it after adding a [JsonSerializable] type to a public context, once the
# rest of the project's surface is recorded (dotnet format analyzers
# --diagnostics RS0016). New lines land in PublicAPI.Unshipped.txt when both
# frameworks record them identically, and in PublicAPI/<tfm>/ when they differ:
# the net10.0 generator marks its JsonTypeInfo properties nullable-oblivious and
# the net8.0 one does not. See src/Directory.Build.targets.
#
# How: build once per framework with the generator's output written to disk,
# remove the [JsonSerializable] attributes so the generator emits nothing,
# compile those files as ordinary sources with the markers `dotnet format`
# treats as generated stripped, and run the code fix one framework at a time.
# Every file it touches is restored on exit, including on failure.
set -euo pipefail
export MSYS_NO_PATHCONV=1

if [ "$#" -lt 2 ]; then
  echo "usage: $0 <project dir> <context .cs file>..." >&2
  exit 2
fi

P="${1%/}"; shift
CTX=("$@")
N="$(basename "$P")"
W="$(mktemp -d)"
# dotnet on Windows cannot resolve an MSYS path such as /tmp/tmp.X.
if command -v cygpath > /dev/null 2>&1; then W="$(cygpath -m "$W")"; fi
S=System.Text.Json.SourceGeneration/System.Text.Json.SourceGeneration.JsonSourceGenerator
TFMS=$(grep -oE '<TargetFrameworks?>[^<]+' "$P/$N.csproj" | sed -E 's/.*>//' | tr ';' ' ')

cp "$P/$N.csproj" "$W/csproj"
cp "$P/PublicAPI.Unshipped.txt" "$W/shared"
for t in $TFMS; do
  mkdir -p "$P/PublicAPI/$t"
  for k in Shipped Unshipped; do
    f="$P/PublicAPI/$t/PublicAPI.$k.txt"
    [ -f "$f" ] || printf '#nullable enable\n' > "$f"
  done
  cp "$P/PublicAPI/$t/PublicAPI.Unshipped.txt" "$W/tfm-$t"
done
for c in "${CTX[@]}"; do cp "$c" "$W/$(basename "$c").orig"; done

restore() {
  rm -rf "$P/_pa_gen"
  cp "$W/csproj" "$P/$N.csproj"
  cp "$W/shared" "$P/PublicAPI.Unshipped.txt"
  for t in $TFMS; do cp "$W/tfm-$t" "$P/PublicAPI/$t/PublicAPI.Unshipped.txt"; done
  for c in "${CTX[@]}"; do cp "$W/$(basename "$c").orig" "$c"; done
}
trap 'restore; rm -rf "$W"' EXIT

for t in $TFMS; do
  # Tracking off, so an unrecorded symbol here or in a referenced project
  # cannot fail the build before the generator's output is written.
  dotnet build "$P/$N.csproj" -f "$t" -c Release -p:PeripheryLocalFeedDisable=true -p:PeripheryTrackPublicApi=false \
    -p:EmitCompilerGeneratedFiles=true "-p:CompilerGeneratedFilesOutputPath=$W/gen-$t" \
    -nologo -v q > "$W/build-$t.log" 2>&1 || true
done

for c in "${CTX[@]}"; do sed -i -E '/^\[JsonSerializable\(/d' "$c"; done

for t in $TFMS; do
  rm -rf "$P/_pa_gen"; mkdir -p "$P/_pa_gen"
  for c in "${CTX[@]}"; do
    k="$(basename "$c" .cs)"
    found=0
    for f in "$W/gen-$t/$S/$k".*g.cs; do
      [ -f "$f" ] || continue
      found=1
      b="$(basename "$f" .g.cs)"
      sed -e '/<auto-generated/d' -e '/GeneratedCodeAttribute/d' "$f" > "$P/_pa_gen/${b//./_}.cs"
    done
    if [ "$found" = 0 ]; then
      echo "no generated sources for $k on $t; see $W/build-$t.log" >&2
      trap - EXIT; restore; exit 1
    fi
  done
  cp "$W/csproj" "$P/$N.csproj"
  sed -i -E "s#<TargetFrameworks>[^<]+</TargetFrameworks>#<TargetFrameworks>$t</TargetFrameworks>#" "$P/$N.csproj"
  cp "$W/shared" "$P/PublicAPI.Unshipped.txt"
  cp "$W/tfm-$t" "$P/PublicAPI/$t/PublicAPI.Unshipped.txt"
  dotnet format analyzers "$P/$N.csproj" --diagnostics RS0016 -v q > "$W/format-$t.log" 2>&1 || true
  # The analyzer sees two Unshipped files and may write to either.
  { grep -vxFf "$W/shared" "$P/PublicAPI.Unshipped.txt" || true
    grep -vxFf "$W/tfm-$t" "$P/PublicAPI/$t/PublicAPI.Unshipped.txt" || true; } | sort -u > "$W/new-$t"
  echo "$N $t: $(wc -l < "$W/new-$t") new line(s)"
done

restore

set -- $TFMS
if [ "$#" = 1 ]; then cp "$W/new-$1" "$W/common"; else comm -12 "$W/new-$1" "$W/new-$2" > "$W/common"; fi
{ echo '#nullable enable'; { grep -v '^#nullable' "$W/shared" || true; cat "$W/common"; } | LC_ALL=C sort -u; } \
  > "$P/PublicAPI.Unshipped.txt"
for t in $TFMS; do
  { echo '#nullable enable'
    { grep -v '^#nullable' "$W/tfm-$t" || true; grep -vxFf "$W/common" "$W/new-$t" || true; } | LC_ALL=C sort -u
  } > "$P/PublicAPI/$t/PublicAPI.Unshipped.txt"
done
trap 'rm -rf "$W"' EXIT
echo "$N: $(wc -l < "$W/common") line(s) shared by both frameworks"
